repos:
  -   repo: https://github.com/Contrast-Labs/detect-secrets
      rev: v1.1.2
      hooks:
        -   id: detect-secrets
            name: Detect secrets
            language: python
            entry: detect-secrets-hook
            args: ['--baseline', '.secrets.baseline']
