export const attackValues: {
    'mongodb.Db.prototype.eval': string;
    'r.insert': string;
    'r.update': string;
    'r.filter': string;
    'r.match': string;
    'r.js': string;
    'aws-sdk.client-dynamodb.ScanCommand.ProjectionExpression': string;
    'aws-sdk.client-dynamodb.ScanCommand.FilterExpression': string;
    'aws-sdk.client-dynamodb.ScanCommand.ComparisonOperator': string;
    'aws-sdk.DynamoDB.DocumentClient.prototype.scan': string;
    'aws-sdk.DynamoDB.prototype.makeRequest': string;
    'mongodb.Collection.prototype.findOneAndUpdate__$where': string;
    'mongodb.Collection.prototype.updateMany__$where': string;
    'mongodb.Collection.prototype.findOne__$function': string;
    'mongodb.Collection.prototype.findOneAndUpdate__$function': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$init': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$accumulate': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$merge': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$finalize': string;
};
export const descriptions: {
    'mongodb.Collection.prototype.findOneAndUpdate__$where': string;
    'mongodb.Collection.prototype.updateMany__$where': string;
    'mongodb.Collection.prototype.findOne__$function': string;
    'mongodb.Collection.prototype.findOneAndUpdate__$function': string;
    'mongodb.Collection.prototype.aggregate__$accumulator': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$init': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$accumulate': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$merge': string;
    'mongodb.Collection.prototype.aggregate__$accumulator__$finalize': string;
};
