export type ResponsePreparer = import("./response-preparers").ResponsePreparer;
export type Param = import("./sinks").Param;
export type SinkParams = import("./sinks").SinkParams;
export type SinkOpts = import("./sinks").SinkOpts;
export type SinkFn = import("./sinks").SinkFn;
export type SinkObj = import("./sinks").SinkObj;
export type Sink = import("./sinks").Sink;
export type InputMap = import("./frameworks").InputMap;
export type FrameworkMap = import("./frameworks").FrameworkMap;
export type Product = import("./routes").Product;
export type Input = import("./routes").Input;
export type Route = import("./routes").Route;
import content = require("./content");
export const navRoutes: Pick<routes.Route, keyof routes.Route>[];
import routes = require("./routes");
import utils = require("./utils");
export { content, routes, utils };
