version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        node_version: 24
    entrypoint: ./entry.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - /app/node_modules
