FROM ubuntu:focal

ARG node_version=14
ARG DEBIAN_FRONTEND=noninteractive

# Update package lists and install dependencies
RUN apt-get update && \
    apt-get install -y curl ca-certificates wget && \
    apt-get install -y curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    curl -sL "https://deb.nodesource.com/node_${node_version}.x" | bash -

# Install Node.js
RUN apt-get install -y nodejs

# Install gnupg2
RUN apt-get update && apt-get install -y gnupg2

# Create the file repository configuration, import the repository signing key and install
RUN echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

RUN apt update
RUN apt-get -y install sudo

# Add PostgreSQL repository and install PostgreSQL 11
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql-11 postgresql-contrib-11 postgresql-client

# Configure such that remote connections to the database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/11/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/11/main/postgresql.conf

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]
EXPOSE 5432

# RethinkDB
RUN echo "deb https://download.rethinkdb.com/repository/debian-buster buster main" > /etc/apt/sources.list.d/rethinkdb.list
RUN wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo apt-key add -v - && apt-get update && apt-get install -y rethinkdb
RUN rm -rf /var/lib/apt/lists/*
VOLUME  ["/etc/rethinkdb", "/var/log/rethinkdb", "/var/lib/rethinkdb"]
EXPOSE 28015

# Install MySQL Database
ENV DEBIAN_FRONTEND="noninteractive"
RUN wget http://repo.mysql.com/mysql-apt-config_0.8.23-1_all.deb
RUN apt update
RUN apt install -y lsb-base lsb-release ./mysql-apt-config_0.8.23-1_all.deb

RUN curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash
RUN apt-get install mariadb-server mariadb-client -y
VOLUME ["/etc/mysql", "/var/lib/mysql"]
EXPOSE 3306

# SQLite DB
RUN apt install sqlite3
RUN sqlite3 --version

# DynamoDB
# At least Java v8.x is required for DynamoDB
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install default-jre-headless -y
RUN java -version
EXPOSE 8

# Install prerequisites
RUN apt-get update && \
    apt-get install -y gnupg curl && \
    curl -fsSL https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - && \
    echo "deb http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list && \
    apt-get update

# Install MongoDB
RUN apt-get install -y mongodb-org

# Expose port 27017
EXPOSE 27017

RUN apt-get update && apt-get install -y build-essential libxml2-dev

# Application setup
WORKDIR /app
COPY . .
RUN chmod +x install-dynamodb-local.sh
RUN ./install-dynamodb-local.sh
RUN npm ci
RUN npm uninstall libxmljs2
RUN npm install libxmljs2
RUN npm rebuild

ENTRYPOINT ["./screener.sh"]
