version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 12
    volumes:
      - .:/app:cached
    command: ./entry.sh
    network_mode: service:mongo

  mongo:
    image: mongo:5
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
