ARG node_version=14
FROM node:${node_version}-stretch

# Create the file repository configuration, import the repository signing key and install
RUN echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt update
RUN apt-get -y install sudo

# PostgreSQL
RUN apt install -y postgresql-10 postgresql-contrib-10 postgresql-client-10
# Configure such that remote connections to the database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/10/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/10/main/postgresql.conf
# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]
EXPOSE 5432

# RethinkDB
RUN echo "deb https://download.rethinkdb.com/repository/debian-stretch stretch main" > /etc/apt/sources.list.d/rethinkdb.list
RUN wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo apt-key add -v - && apt-get update && apt-get install -y rethinkdb
RUN rm -rf /var/lib/apt/lists/*
VOLUME  ["/etc/rethinkdb", "/var/log/rethinkdb", "/var/lib/rethinkdb"]
EXPOSE 28015

# MySQL Database
ENV DEBIAN_FRONTEND="noninteractive"
RUN wget http://repo.mysql.com/mysql-apt-config_0.8.13-1_all.deb
RUN apt update
RUN apt install lsb-base lsb-release ./mysql-apt-config_0.8.13-1_all.deb
RUN apt install mysql-server mysql-client -y
VOLUME ["/etc/mysql", "/var/lib/mysql"]
EXPOSE 3306

# SQLite DB
RUN apt install sqlite3
RUN sqlite3 --version

## Java: At least Java v8.x is required for DynamoDB
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install default-jre -y
RUN java -version

# Application setup
WORKDIR /app
COPY . .
RUN npm ci

ENTRYPOINT ["./screener.sh"]
