name: ECR Push

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # not all apps support node versions below, but at the very
        # least they all build
        apps: [express,fastify,hapi18,hapi19,hapi20,koa,kraken,loopback,loopback4,restify,sails]
        version: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image ${{ matrix.apps }} version ${{ matrix.version }} to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.apps }}
          IMAGE_TAG: ${{ github.sha }}
          NODE_VERSION: ${{ matrix.version }}
        run: |
          cd $ECR_REPOSITORY
          ../scripts/copy-scripts.sh
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-$NODE_VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY:latest-$NODE_VERSION --build-arg node_version=$NODE_VERSION .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
