name: ECR Push

on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # not all apps support node versions below, but at the very
        # least they all build
        apps: [express4,express5,fastify3,hapi18,hapi19,hapi20,koa,kraken,loopback,loopback4,restify,sails]
        version: [14, 16, 18, 20]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Configure AWS credentials
        uses: step-security/configure-aws-credentials@784445aed640b0a6f03906d26d690532d4fe6c6b # v6.2.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: step-security/amazon-ecr-login@b8045438dc204276b62463a5e3cfedca8cb0dca0 # v2.1.6

      - name: Build, tag, and push image ${{ matrix.apps }} version ${{ matrix.version }} to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.apps }}
          NODE_VERSION: ${{ matrix.version }}
        run: |
          cd $ECR_REPOSITORY
          ../scripts/copy-scripts.sh
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest-$NODE_VERSION --build-arg node_version=$NODE_VERSION .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
