name: Test

on:
  push:
    branches: [main]
      - main
  pull_request:
    branches: ['*']

jobs:
  test:
    name: Node v${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node v${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - name: Install dependencies
        shell: bash
        run: npm install -g npm@8 && npm ci
      - name: Run tests
        shell: bash
        run: npm test
