name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  test:
    name: Node v${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20, 22, 24]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Set up Node v${{ matrix.version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.version }}
      - name: Install dependencies
        shell: bash
        run: npm install -g npm@8 && npm ci
      - name: Run tests
        shell: bash
        run: npm test
